/**
 * @file shared/channels.ts
 * @description IPC 通道名常量,主进程和预加载脚本共同引用,避免裸字符串拼写错误
 */

export const IPC = {
  GET_CONNECTION: 'get-connection',
  GET_DEVICES: 'get-devices',
  DEVICE_UPSERT: 'device:upsert',
  DEVICE_RENAME: 'device:rename',
  DEVICE_REMOVE: 'device:remove',
  SWITCH_HOST: 'switch-host',
  CONNECTION_CHANGED: 'connection:changed',
  SELECT_FOLDER: 'select-folder',
  STATE_GET_ALL: 'state:get-all',
  STATE_SET: 'state:set',
  STATE_DELETE: 'state:delete',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_UNMAXIMIZE: 'window:unmaximize',
  WINDOW_CLOSE: 'window:close',
  WINDOW_IS_MAXIMIZED: 'window:is-maximized',
  WINDOW_MAXIMIZED_CHANGED: 'window:maximized-changed',
  LOG: 'log',
  SET_LOGGING_ENABLED: 'set-logging-enabled',
  PROXY_FETCH: 'proxy-fetch',
  OPEN_EXTERNAL: 'open-external',
  OPEN_PATH: 'open-path',
  UPDATER_GET_VERSION: 'updater:get-version',
  UPDATER_CHECK_FOR_UPDATES: 'updater:check-for-updates',
  UPDATER_DOWNLOAD_UPDATE: 'updater:download-update',
  UPDATER_INSTALL_UPDATE: 'updater:install-update',
  UPDATER_STATUS_CHANGED: 'updater:status-changed',
  UPDATER_DOWNLOAD_PROGRESS: 'updater:download-progress',
  CACHE_CHANGED: 'cache:changed',
  CACHE_GET_SESSIONS: 'cache:get-sessions',
  CACHE_GET_SESSION: 'cache:get-session',
  CACHE_GET_AGENTS: 'cache:get-agents',
  CACHE_GET_CURSOR: 'cache:get-cursor',
  CACHE_APPLY_SNAPSHOT: 'cache:apply-snapshot',
  CACHE_APPLY_CHANGES: 'cache:apply-changes',
  CACHE_PUT_AGENTS: 'cache:put-agents',
  CACHE_DELETE_AGENT: 'cache:delete-agent',
  CACHE_RESET: 'cache:reset',
} as const;
